### ISSUE TITLE
빠른 상담 요청 테두리 효과

### ISSUE THREAD

**Issue by BBZJUN** [hanaro4-dIA/dia_pb_fe#102]
## 📝설명
ScheduledConsultationList 과 ConsultationRequest에서 빠른 상담 요청의 경우에는 상단 정렬과 빨간 두꺼운 테두리 설정

## ✅ TO-DO
- [x] Consultings.json에 quick에 대한 boolean 추가
- [x] type.ts 수정 (quick:boolean // 빠른 상담 요청 여부 , 빠른 상담 요청의 경우 title,category,inquiryDetails ?로 선택 설정)
- [x] 테두리 추가
- [x] 타이머 추가
- [x] 반짝이는 애니메이션을 위한 index.css 수정
