### ISSUE TITLE
ERD를 반영한 데이터 칼럼명 변경

### ISSUE THREAD

**Issue by KyoungEun-creator** [hanaro4-dIA/dia_pb_fe#121]
## 📝설명

ERD 내 칼럼명 반영 및 변경사항 수정할 것

## ✅ TO-DO

- [x] PB 개인정보 타입 (PB.json)
- [x] PB가 관리하는 손님 (Customer_PB.json)
- [x] 상담 카테고리 타입 (Category.json)
- [x] 손님 타입 (Customers.json)
- [x] 쪽지 타입 (Notifications.json)
- [x] DB 키워드 타입 (dictionary.ts)

## 🚀기타
기타 사항을 작성해 주세요
