### ISSUE TITLE
상담일지 작성하기 내 메타데이터 수정 가능하게 변경

### ISSUE THREAD

**Issue by KyoungEun-creator** [hanaro4-dIA/dia_pb_fe#122]
## 📝설명
상담일지 작성하기 내 메타데이터 수정 가능하게 변경

## ✅ TO-DO
- [x] 상담제목, 카테고리 null 일 경우 '빠른 상담'으로 들어갈 것
- [x] 카테고리 드랍다운 메뉴로 변경할 것
- [x] ConsultationJournalList 내 item 내 key prop 넣어줄 것

## 🚀기타
기타 사항을 작성해 주세요
