### ISSUE TITLE
dictionary 페이지 열람 시 로그인 풀려버리는 오류 

### ISSUE THREAD

**Issue by KyoungEun-creator** [hanaro4-dIA/dia_pb_fe#124]
## 📝설명
로그인이 되어있는 상태에서 
NavigationBtn을 눌러 dictionaryPage를 new tab으로 열었을 때
new tab에서의 dictionaryPage가 로그인을 하지 않은 것으로 알고 로그인페이지로 리다이렉트 시켜버림

## ✅ TO-DO
- [x] localStorage에 로그인 정보가 들어있는지 유무에 따라 로그인 여부 파악할 것
- [x] 로그아웃 버튼 클릭 시 새로고침을 해야 /login으로 이동하는 오류 해결
- [x] 로그아웃 후에도 /dictionary 페이지 안에서 NavigationBtn 통한 타 페이지 이동 가능한 오류 해결 
       (새로고침 해야 로그아웃 상태임을 인식함)

## 🚀기타
기타 사항을 작성해 주세요

**Comment by KyoungEun-creator** [comment]
로그아웃 후 localStorage 내 user 정보 인식 위해 
handleLogoutEvent 내 window.location.reload()

**Comment by KyoungEun-creator** [comment]
로그아웃 후에도 /dictionary 페이지 안에서 NavigationBtn 통한 타 페이지 이동 가능한 오류 해결 위해
App.tsx 파일 내 useEffect를 이용해 navigate와 isLogin 상태를 추적하고 
변화가 있을 경우 /login으로 이동하도록 함
