### ISSUE TITLE
/dictionary 페이지 UI 수정

### ISSUE THREAD

**Issue by KyoungEun-creator** [hanaro4-dIA/dia_pb_fe#130]
## 📝설명
키워드 DB의 상세 URL 사용하지 않음

## ✅ TO-DO
- [x] 상세 URL UI 삭제할 것
- [x] Dictionary.ts 목업데이터 수정
- [x] TDbItemProps data type 수정

## 🚀기타
기타 사항을 작성해 주세요
