### ISSUE TITLE
최종 ERD 및 목업데이터에 따른 json 데이터 변경

### ISSUE THREAD

**Issue by KyoungEun-creator** [hanaro4-dIA/dia_pb_fe#131]
## 📝설명
최종 ERD 및 목업데이터에 따른 json 데이터, 칼럼 명, type정의 변경
컴포넌트에서 받는 데이터 수정

## ✅ TO-DO
- [x] PB.json
- [x] Notifications.json, TNotificationProps
- [x] Dictionary.ts -> DictionaryDetail.tsx
- [x] Customers.json, TCustomersProps
- [x] Consultings.json, TRequestedConsultationsProps

## 🚀기타
기타 사항을 작성해 주세요
