### ISSUE TITLE
상담일지 작성 페이지 (consulting/{consultingId}) UI 수정

### ISSUE THREAD

**Issue by KyoungEun-creator** [hanaro4-dIA/dia_pb_fe#142]
## 📝설명
수정 배경 >
- 'STT 자동 작성란' 이라는 이름이 개발자가 아닌 일반 사용자(pb) 친화적이지 않다는 판단
- STT 내용 저장 및 키워드 추출 작동 용도를 가진 버튼 ‘저장’의 이름이 명시적이지 않아 부적절하다는 판단

## ✅ TO-DO
- [x] STT 컴포넌트의 섹션 타이틀 ‘상담 스크립트’로 변경
- [x] 키워드 추출용 버튼 '적용'으로 변경
- [x] MakeJournal 컴포넌트 내 textarea 간 간격 조정

## 🚀기타
기타 사항을 작성해 주세요
