### ISSUE TITLE
메인페이지 및 손님관리페이지 수정

### ISSUE THREAD

**Issue by BBZJUN** [hanaro4-dIA/dia_pb_fe#22]
## 📝설명
손님 목록 컴포넌트, 요청된 상담 리스트 컴포넌트, 예정된 상담 리스트 컴포넌트에 대해서
json불러오기 및 손님에 맞는 정보로 업데이트 되는 기능 추가

## ✅ TO-DO
- [x] 손님 목록에서 손님  클릭으로 손님 디테일 페이지 이동 추가
- [x] 해당 손님 정보로 업데이트 되면서 페이지 이동
- [x] 상담 json 생성

## 🚀기타
기타 사항을 작성해 주세요
