### ISSUE TITLE
들어온 상담 요청에서 승인버튼 클릭 시 예정된 상담 일정 컴포넌트로 바로 이동 안됨 오류 해결

### ISSUE THREAD

**Issue by KyoungEun-creator** [hanaro4-dIA/dia_pb_fe#223]
## 📝설명
들어온 상담 요청에서 승인버튼 클릭 시 
1. 들어온 상담 요청 컴포넌트에서 승인버튼이 클릭된 아이템 요소 제거됨
2. 예정된 상담 일정 컴포넌트에서 승인버튼이 클릭된 아이템 요소 추가됨

## ✅ TO-DO
- [x] isRefetch 값이 바뀔 때 fetchData를 다시 하도록 시행
- [x] 섹션 명 변경: '예정된 상담 일정' -> '미완료 상담 일정 및 일지'
- [x] MakeJournal, PbCalendar 컴포넌트 연결 api 변경

## 🚀기타
기타 사항을 작성해 주세요
