### ISSUE TITLE
JSON 파일들 타입 정의된 파일 분리

### ISSUE THREAD

**Issue by KyoungEun-creator** [hanaro4-dIA/dia_pb_fe#26]
## 📝설명
types.ts 파일 분리

## ✅ TO-DO
- [x] types.ts 파일에 JSON 데이터들에 대한 타입 정의 모아놓기
- [x] (Consultings.json) topic → title, category
- [x] hopeDay, hopeTime 추가
- [x] inquiryDetails 추가
- [x] approvalStatus: string → boolean 타입 변경
- [x] (PB.json) businessId: number ( 사번 )
- [x] 타입 변화로 인한 버그 전부 수정

**Comment by KyoungEun-creator** [comment]
끝났당~~야호🙌🙌
