### ISSUE TITLE
상담일지 자세히보기, 예정된 상담에서 컨설팅 페이지 이동 추가(+전체적인 코드 수정)

### ISSUE THREAD

**Issue by BBZJUN** [hanaro4-dIA/dia_pb_fe#28]
## 📝설명
상담일지를 누르면 자세히보기의 모달창 나오게 끔 추가
예정된 상담 일정에서 상담하기 버튼을 누르면 해당 손님의 해당 일정의 컨설팅 페이지로 이동 추가
[#fff] -> white 수정
Category.json 생성
types에 Category.json 관련 type 생성 
날짜형식 통일

## ✅ TO-DO
- [x] 상담일지를 누르면 자세히보기의 모달창 나오게 추가
- [x] 예정된 상담 일정에서 상담하기 버튼을 누르면 해당 손님의 해당 일정의 컨설팅 페이지로 이동 추가
- [x] [#fff] -> white 수정
- [x] Category.json 생성
- [x] types에 Category.json 관련 type 생성
- [x] 날짜형식 yyyy.mm.dd 통일

## 🚀기타
기타 사항을 작성해 주세요

**Comment by KyoungEun-creator** [comment]
고생 많으셨어요~~~!!👍👍
