### ISSUE TITLE
PbCalendar Modal

### ISSUE THREAD

**Issue by larchlarix** [hanaro4-dIA/dia_pb_fe#30]
## 📝설명
PbCalendar Modal 수정
외부 영역 클릭시에도 모달 닫히게 하기,
모달 내부 요소 시간 오름차순 정렬하기

## ✅ TO-DO
- [x] 외부 영역 클릭시 모달 닫히게
- [x] 모달 내부 요소 시간 오름차순 정렬
- [x] 모달 내부 text 위치 가운데 정렬 
- [x] destructuring

**Comment by KyoungEun-creator** [comment]
고생하셨습니다!!👍👍
destructuring까지!!최고최고!!
