### ISSUE TITLE
들어온 상담 요청 컴포넌트와 상담 일정 컴포넌트 연결 / 손님 정보 컴포넌트 메모 수정 / 전체 컴포넌트들 배경 및 테두리 수정

### ISSUE THREAD

**Issue by BBZJUN** [hanaro4-dIA/dia_pb_fe#40]
## 📝설명
<들어온 상담 요청 컴포넌트 & 상담 일정 컴포넌트>
1. 승인대기 버튼 누르면 상담 일정 컴포넌트로 전달되게끔
2. 날짜에 따른 오름차순 정렬

<손님 정보 컴포넌트>
1. 메모에서 EDIT말고 펜슬같은 아이콘으로

<전체 컴포넌트들>
1. 겹치는 배경, border 정리

## ✅ TO-DO
- [x] 승인대기 버튼 누르면 상담 일정 컴포넌트로 전달되게끔
- [x] 날짜에 따른 오름차순 정렬
- [x] 메모에서 EDIT말고 펜슬같은 아이콘으로 변환
- [x] 겹치는 배경, border 정리
