### ISSUE TITLE
consulting page 내 디자인 재수정

### ISSUE THREAD

**Issue by KyoungEun-creator** [hanaro4-dIA/dia_pb_fe#48]
## 📝설명
consulting page 내 디자인 재수정

## ✅ TO-DO
- [x] 손님정보 메모란 불필요한 스크롤 없애기
- [x] STT 자동 작성란 제목 두께 통일하기
- [x] 상담일지 작성하기에 '상담 스크립트' 전에 '추천 상품' 기입란 추가하기
- [x] STT 자동 작성란 전체 길이 맞추기
- [x] 상담일지 리스트 전체 길이 맞추기
- [x] '딕셔너리 바로가기' 버튼 생성하기
