### ISSUE TITLE
전체적인 디자인 재점검

### ISSUE THREAD

**Issue by KyoungEun-creator** [hanaro4-dIA/dia_pb_fe#56]
## 📝설명
전체적인 디자인 및 코드 재점검
 
## ✅ TO-DO
- [x] 캘린더, 예정된 상담 일정란의 타이틀 변경
- [x] PbProfile 태그 위치 및 크기, 한줄소개란 수정
- [x] GuestList 클릭한 손님 디자인 수정
- [x] CustomerDetailPage 두 번째 열 길이 수정
- [x] props 및 params 최대한 destructuring 진행
