### ISSUE TITLE
타입 정리

### ISSUE THREAD

**Issue by BBZJUN** [hanaro4-dIA/dia_pb_fe#58]
## 📝설명
any, 중복되는 타입 삭제
types 파일에 있는 타입 import하여 사용
타입 선언 형식 맞추기 (T~props)

## ✅ TO-DO
- [x] any, 중복되는 타입 삭제
- [x] types 파일에 있는 타입 import하여 사용
- [x] 타입 선언 형식 맞추기 (T~props)
