### ISSUE TITLE
ConsultingPage 내 버그 수정 및 STT 시작

### ISSUE THREAD

**Issue by KyoungEun-creator** [hanaro4-dIA/dia_pb_fe#66]
## 📝설명
ConsultingPage 내 버그 수정 및 STT 시작

## ✅ TO-DO
- [x] [PB의 기록] 중복 문제 해결
- [x] ConsultingPage 내 열마다 너비 조정
- [x] STT 자동 작성란 길이 및 제목폭 오류 수정
- [x] 상담일지 리스트 길이 넘어감 오류 수정
- [x] 상담일지 작성란 내 요청내용 자세히 보기를 별도의 창으로 분리
