### ISSUE TITLE
dictionary 관련 변경사항 

### ISSUE THREAD

**Issue by KyoungEun-creator** [hanaro4-dIA/dia_pb_fe#70]
## 📝설명
dictionary 관련 UI 수정 

## ✅ TO-DO
- [ ] 기존에 있던 키워드 DB 목록 바로가기 버튼 제거
- [ ] DictionaryPage 내 불필요한 칼럼 삭제
- [ ] 클릭된 키워드 아이템에 테두리 처리
- [ ] 키워드 상세보기 윈도우 내 작성자, 최근업데이트날짜 삭제

## 🚀기타
기타 사항을 작성해 주세요
