### ISSUE TITLE
navigation btn 만들기

### ISSUE THREAD

**Issue by KyoungEun-creator** [hanaro4-dIA/dia_pb_fe#71]
## 📝설명
- Home 화면으로 바로 이동할 수 있기 위한 네비게이션의 필요성에서 기인함
- 어느 페이지에서든 dictionary 페이지를 바로 열 수 있도록 함
- 쪽지 보내기 기능의 경우 자주 사용하지 않기 때문에 navigation btn 클릭 시 보여지는 네비게이션을 통해 열 수 있게끔 함

## ✅ TO-DO
- [x] 사용자가 click and drag를 통해 위치시키는 곳에 놓아지는 기능
- [x] 클릭 시 세 개의 링크 버튼이 보여짐
- [x] HOME으로 이동 (/)
- [x] 키워드 DB 목록 바로가기 (/dictionary)
- [x] 손님에게 마음 보내기 (/notification)
- [x] 버튼이 가장자리에만 위치하는 기능

## 🚀기타
기타 사항을 작성해 주세요
