### ISSUE TITLE
[consulting/:id] 상담일지 페이지 내 변경사항

### ISSUE THREAD

**Issue by KyoungEun-creator** [hanaro4-dIA/dia_pb_fe#72]
## 📝설명
consulting/:id 상담일지 페이지 내 변경사항

## ✅ TO-DO
- [x] 상담일지 리스트 영역 내 검색기능 추가 @KyoungEun-creator 
- [x] 검색창 컴포넌트 따로 빼서 재사용하기 @KyoungEun-creator 
- [x] 상담일지 작성란 내 상단 메타데이터 수정 (카테고리, 담당PB, 상담일시만 남겨놓기) @larchlarix 
- [x] 상담일지 작성란 내 상담스크립트 작성란 삭제 @larchlarix 

## 🚀기타
기타 사항을 작성해 주세요
