### ISSUE TITLE
이전에 전송한 쪽지 컴포넌트 구현

### ISSUE THREAD

**Issue by BBZJUN** [hanaro4-dIA/dia_pb_fe#83]
## 📝설명
NotiHistory.tsx 컴포넌트 제작

## ✅ TO-DO
- [ ] 전체선택 체크박스 제작
- [ ] 손님 선택 검색창 제작
- [ ] 체크된 손님의 경우, 태그로 체크됨 표시
- [ ] 손님 선택 Drop Down 제작
- [ ] 파일안의 예제 코드 제작

## 🚀기타
컴포넌트 입니다.
