### ISSUE TITLE
검색창 관련 기능 추가 및 오류 해결

### ISSUE THREAD

**Issue by KyoungEun-creator** [hanaro4-dIA/dia_pb_fe#86]
## 📝설명
- 스크롤 하더라도 검색창은 상단에 고정되도록 하는 기능 추가 
- GuestList에서 검색결과 없을 경우 예외처리
- 손님 목록 영역 내 검색 결과 없을 경우 height 줄어드는 오류 해결

## ✅ TO-DO
- [x] GuestList 손님목록 내 검색창 상단 고정
- [x] ConsultationJournalList 상담일지 리스트 내 검색창 상단 고정
- [x] DictionaryPage 키워드 DB 목록 내 검색창 상단 고정
- [x] GuestList에서 검색결과 없을 경우 예외처리
- [x] MainPage 내 손님 목록 영역 height
- [x] CustomerDetailPage 내 손님 목록 영역 height

## 🚀기타
기타 사항을 작성해 주세요
